### ISSUE TITLE
Kreditkartenzahlung nicht möglich

### ISSUE THREAD

**Issue by mdeekenEMOTIVO** [shopware5/SwagPaymentPayPalUnified#45]
Hi, wir haben in einem Shopware 5 Store das Problem, dass Kreditkartenzahlungen über PayPal immer abgelehnt werden. Der PayPal-Support hat gesagt, es liegt nicht an ihnen und wir sollen ein Ticket bei Shopware für das Problem eröffnen.

<img width="1009" alt="chrome_4ahAupew1K" src="https://github.com/shopware5/SwagPaymentPayPalUnified/assets/78587486/ba67ced0-3678-425b-8a85-e2b2f323d411">
<img width="311" alt="OUTLOOK_ZR18RGDKq7" src="https://github.com/shopware5/SwagPaymentPayPalUnified/assets/78587486/35d2a648-8ca7-4bf7-b3f4-86a84c1fd5df">

**Comment by swDennis** [comment]
Hallo, kannst du mal schauen, ob du diese Option vllt. angeschaltet hast.

![acdc settings](https://github.com/shopware5/SwagPaymentPayPalUnified/assets/11271248/c41ead56-44db-4a99-b466-b331014fa275)

**Comment by mdeekenEMOTIVO** [comment]
Moin, nein der Haken ist nicht gesetzt. Laut PayPal ist Kreditkarte freigeschaltet. Beim Verfügbarkeitstest sagt er auch das es freigeschaltet ist.
![image](https://github.com/shopware5/SwagPaymentPayPalUnified/assets/78587486/d87b7c8b-b676-495f-8a0f-2e4e5cc00155)

**Comment by swDennis** [comment]
Hmm, der Status der Zahlung ist DECLINED also "abgelehnt". Ist es den mit jeder Kreditkarte oder nur mit bestimmten? Du hast oben "immer" geschrieben. Das spricht doch sehr dafür, dass dein Account nicht für Kreditkarten Zahlungen freigegeben wurde.

Nach Tests mit einer Sandbox Umgebung kann ich sagen, dass es kein Problem mit dem Plugin ist. 

Ich würde nochmal mit dem PayPal Support sprechen und einen Test zusammen mit denen durchgehen. Die können anhand der Requests schnell sehen, wo das Problem liegt.

**Comment by mdeekenEMOTIVO** [comment]
Okay danke ich werde das nochmal in Erfahrung bringen.

**Comment by mdeekenEMOTIVO** [comment]
Wir haben jetzt dem PayPal Support geschrieben. Kreditkarte ist aktiviert. Von denen kam jetzt die Info das Shopware eine Rechnungs-ID übergibt, die bereits vergeben ist. 

![image](https://github.com/shopware5/SwagPaymentPayPalUnified/assets/78587486/76aaf113-8dcc-4f9f-ae02-f5c4046ab08f)

**Comment by swDennis** [comment]
Hmm, das ist in der Tat seltsam. Man kann im PayPal Admin einstellen, ob man doppelte Rechnungs-ID zulässt oder nicht. Außerdem solltest du einmal die Tabelle `swag_payment_paypal_unified_order_number_pool` komplett leeren. Vllt. beseitigt es das Problem schon. Die "Rechnungs-ID", die wir mitschicken, ist eh nur die Bestell-Id, da die Rechnung zu diesem Zeitpunkt noch nicht existiert.

**Comment by mdeekenEMOTIVO** [comment]
Die DB Tabelle ist bereits leer. Ist es diese Einstellung im PayPal Admin Bereich?
![image](https://github.com/shopware5/SwagPaymentPayPalUnified/assets/78587486/6d249f5a-0dee-46c3-b555-baf40ce29b9b)

**Comment by swDennis** [comment]
Ja, das sollte die Einstellung sein. Da müsstest du "Nein" anhaken.

**Comment by mdeekenEMOTIVO** [comment]
Moin, das hat leider auch nichts gebracht.

**Comment by mdeekenEMOTIVO** [comment]
Okay, danke dir. Ich beobachte die Logs mal. Wir werden den PayPal-Support erneut kontaktieren. In anderen Shops von uns läuft das Plugin in dieser Version ebenfalls problemlos

**Comment by mitelg** [comment]
Hallo @mdeekenEMOTIVO 

fürs Erste werden wir das Issue hier schließen. Falls es wieder zu Problemen kommen sollte, kannst du gerne ein neues Issue erstellen.
